global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 0.5 # 1.0 before
   publish_frequency: 0.5 # 1.0 before
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: true
   rolling_window: false
